[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/who-data.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/german-data.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/uheft-data.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "no-cache"
